### ISSUE TITLE
更新后炸了啊

### ISSUE THREAD

**Issue by TuKun33** [panhezeng/vue-tinymce#1]
官方的cdn更新的老版本跑不了报错，

我再更新了vue-tinymce

这个包找不到了
https://cdn.jsdelivr.net/npm/tinymce@~5/themes/modern/theme.js net::ERR_ABORTED 404

**Comment by panhezeng** [comment]
升级到tinymce 5以后，本项目的默认配置文件已经没有配置模板属性，tinymce 5已经没有modern模板。

现在已经锁定为tinymce 5，不会出现tinymce大版本升级造成本项目无法运行的问题。如果tinymce再升级到6，还有什么大变动的话，我会及时更新的。

现在示例和我已经在生产部署的项目，都在使用基于tinymce 5的新vue-tinymce，没有问题。您的这个问题，在某个阶段确实出现过，可能是缓存之类问题，请先uninstall vue-tinymce tinymce，重新install vue-tinymce tinymce，并且清除浏览器缓存。

检查下package.json的版本

    "tinymce": "^5.0.3",
    "vue": "^2.6.0"
   "@panhezeng/vue-tinymce": "^2.0.0"
