### ISSUE TITLE
请问一下作者，原tinymce的自定义按钮功能还存在吗？是否可以给个demo看看，另外问一句，通过自定义按钮insertContent一个span标签，如何给这个标签绑定点击事件呢，谢谢！

### ISSUE THREAD

**Issue by lijian8800** [panhezeng/vue-tinymce#2]

**Comment by panhezeng** [comment]
可以自定义按钮，见官方文档 https://www.tiny.cloud/docs/migration-from-4x/#tinymce5-onaction

可以加脚本，见官方文档 https://www.tiny.cloud/docs/configure/url-handling/#allow_script_urls

多查官方文档，有个中文版，但是最好以官方英文为准。http://tinymce.ax-z.cn/
